// Goal Bank for SLP Pink Studio
// This file contains a large set of goals grouped by target area.
// Each property in the GOAL_BANK object corresponds to a target area
// and is associated with an array of goals for that area.

export const GOAL_BANK = {
  "AAC": [
    "Transport his/her device when transitioning between activities or locations",
    "Use word prediction effectively",
    "Access his/her device when needed",
    "Ask for help when the device does not work",
    "Adjust the voice/volume of the device depending on context",
    "Navigate between the main page and one other page",
    "Navigate between the main page and two other pages",
    "Navigate between the main page and three other pages",
    "Navigate between the main page and four other pages",
    "Navigate between the main page and other pages",
    "Select the more appropriate strategy (e.g., single word buttons, spelling, word prediction)",
    "Self\u2011correct errors/miss\u2011hits",
    "Request help",
    "Request desired objects/actions",
    "Request a turn",
    "Request recurrence (e.g., more)",
    "Protest undesired objects/actions",
    "Gain attention",
    "Greet others",
    "Introduce him/herself",
    "Make contextually appropriate comments",
    "End a conversation",
    "Express agreement or disagreement",
    "Talk about current events",
    "Tell about a past event",
    "Tell about a future event",
    "Tell a personal narrative",
    "Retell a story",
    "Request clarification",
    "Ask relevant questions",
    "Ask partner\u2011focused questions",
    "Respond to 'yes/no' questions to indicate choice",
    "Respond to 'yes/no' questions to provide information",
    "Respond to 'who' questions",
    "Respond to 'what' questions",
    "Respond to 'where' questions",
    "Respond to 'when' questions",
    "Respond to 'why' questions",
    "Respond to 'how' questions",
    "Initiate interaction",
    "Take turns in a conversation",
    "Maintain a conversation by asking questions",
    "Maintain a conversation by commenting",
    "Tell jokes",
    "Compliment others",
    "Give directions/instructions",
    "Use 10 words per week",
    "Use 20 words per week",
    "Use 30 words per week",
    "Use 40 words per week",
    "Use polite social forms (i.e., 'please', 'thank you')",
  ],
  "Articulation": [
    "Produce /p/",
    "Produce /b/",
    "Produce /t/",
    "Produce /d/",
    "Produce /m/",
    "Produce /n/",
    "Produce /h/",
    "Produce /f/",
    "Produce /v/",
    "Produce /k/",
    "Produce /g/",
    "Produce 'ch'",
    "Produce 'j'",
    "Produce 'sh'",
    "Produce /l/",
    "Produce /s/",
    "Produce /z/",
    "Produce /l/\u2011blends",
    "Produce /s/\u2011blends",
    "Produce /r/\u2011blends",
    "Produce 'th'",
    "Produce 'ng'",
    "Produce /r/",
    "Produce 2\u2011syllable words",
    "Produce 3\u2011syllable words",
    "Produce 4\u2011syllable words",
    "Produce intelligible words",
  ],
  "Fact & Opinion": [
    "Explain what a fact is",
    "Explain what an opinion is",
    "Identify statements as fact or opinion",
    "Explain why a given statement is a fact/opinion",
    "Provide one detail to support a fact",
    "Provide one detail to support an opinion",
    "Provide two details to support a fact",
    "Provide two details to support an opinion",
    "Provide three details to support a fact",
    "Provide three details to support an opinion",
  ],
  "Fluency": [
    "Describe how the speech machine works",
    "Describe affective and cognitive reactions to stuttering (as documented in his/her speech notebook)",
    "Describe the types of stuttering (e.g., prolongation, sound repetition)",
    "Identify the types of stuttering (e.g., prolongation, sound repetition) in his/her own speech",
    "Describe fluency techniques (e.g., easy start, light contact, pausing and phrasing)",
    "Use fluency techniques (e.g., easy start, light contact, pausing and phrasing)",
    "Describe strategies to decrease tension when speaking (e.g., cancellation, pull out, preparatory set)",
    "Use strategies to decrease tension when speaking (e.g., cancellation, pull out, preparatory set)",
    "Describe self\u2011disclosure and how it can help people who stutter",
    "Self\u2011disclose to individuals selected by the student (e.g., a teacher or a friend)",
  ],
  "Functional Communication": [
    "Engage in joint attention",
    "Choose between two items",
    "Point to request desired objects",
    "Use gestures to request desired objects or actions",
    "Use gestures to protest undesired objects or actions",
    "Use words to request desired objects or actions",
    "Use words to protest undesired objects or actions",
    "Use vocalizations to gain attention",
    "Use words to gain attention",
    "Use vocalizations to greet others",
    "Use words to greet others",
    "Answer yes/no questions",
    "Produce 2\u2011word utterances",
    "Produce 3\u2011word utterances",
    "Produce 4\u2011word utterances",
  ],
  "Grammar": [
    "Produce 3\u2011word sentences that are grammatically correct",
    "Produce 4\u2011word sentences that are grammatically correct",
    "Produce 5\u2011word sentences that are grammatically correct",
    "Produce action + object (e.g., wash hands) phrases",
    "Produce agent + action (e.g., I jump)",
    "Produce action + modifier (e.g., jump fast)",
    "Use prepositions",
    "Use modifiers",
    "Use words to indicate spatial locations (e.g., in, on, over, above)",
    "Use words to indicate spatial relationships (e.g., with, next to, between, among)",
    "Use adverbs to modify verbs based on distance and time (e.g., far, sometimes, early, never, short, always, immediately)",
    "Use regular plural nouns",
    "Use irregular plural nouns",
    "Use subject pronouns (he, she, they)",
    "Use possessive pronouns (my, her, his)",
    "Use helping verbs (is, are, am)",
    "Use modal and auxiliary verbs (e.g., could, would, may, might)",
    "Use past tense verbs",
    "Use irregular past tense verbs",
    "Produce grammatically correct sentences",
    "Produce compound sentences using conjunctions (e.g., and, but, so)",
    "Produce complex sentences using conjunctions (e.g., before, because)",
    "Point to a picture that represents a given auxiliary verb ('is' or 'are' + verbing)",
    "Point to a picture that represents a given pronoun",
    "Point to a picture that represents a given possessive noun (e.g., girl's)",
    "Point to a picture that represents a given comparative (adjective + 'er')",
    "Point to a picture that represents a given superlative (adjective + 'est')",
  ],
  "Phonological Processes": [
    "Reduce backing by producing /t/ and /d/",
    "Reduce fronting by producing /k/ and /g/",
    "Reduce gliding by producing /l/ and /r/",
    "Reduce stopping by producing /f/ and /v/",
    "Reduce stopping by producing /s/ and /z/",
    "Reduce stopping by producing /f/ and /s/",
    "Reduce stopping by producing /v/ and /z/",
    "Reduce stopping by producing 'sh', 'ch', and 'j'",
    "Reduce stopping by producing 'th'",
    "Reduce stopping by producing fricatives",
    "Reduce stopping by producing affricates",
    "Reduce vowelization by producing /l/",
    "Reduce final consonant deletion by producing final consonants",
    "Reduce initial consonant deletion by producing initial consonants",
    "Reduce cluster reduction by producing clusters",
    "Reduce syllable deletion by producing 2\u2011syllable words",
    "Reduce syllable deletion by producing 3\u2011syllable words",
    "Reduce syllable deletion by producing 4\u2011syllable words",
    "Reduce prevocalic voicing by producing prevocalic voiceless consonants",
    "Reduce final consonant devoicing by producing final voiced consonants",
  ],
  "Receptive Language": [
    "Follow 2\u2011step directions",
    "Follow 3\u2011step directions",
    "Answer yes/no questions",
    "Answer questions (who, what)",
    "Answer questions (when, where)",
    "Answer questions (how, why)",
    "Answer WH questions (who, what, when, where, why)",
  ],
  "Vocabulary": [
    "Define grade level vocabulary words",
    "Use context clues to define unknown words",
    "Define idioms",
    "Define the meaning of a figurative statement using literal language",
    "Define multiple meaning words",
    "Name objects",
    "Identify spatial concepts",
    "Name spatial concepts",
    "Identify temporal concepts",
    "Name temporal concepts",
    "Identify qualitative concepts",
    "Name qualitative concepts",
    "Identify quantitative concepts",
    "Name quantitative concepts",
    "Identify comparatives (e.g., big/bigger, small/smaller)",
    "Name comparatives (e.g., big/bigger, small/smaller)",
    "Identify superlatives (e.g., smallest, biggest)",
    "Name superlatives (e.g., smallest, biggest)",
    "Sort items by category",
    "Name items in categories",
    "Name a category when given three items",
    "Describe an item using 2/7 descriptors (e.g., category, function, appearance, parts, location)",
    "Describe an item using 3/7 descriptors (e.g., category, function, appearance, parts, location)",
    "Describe an item using 4/7 descriptors (e.g., category, function, appearance, parts, location)",
    "Describe an item using 5/7 descriptors (e.g., category, function, appearance, parts, location)",
    "Describe an item using 6/7 descriptors (e.g., category, function, appearance, parts, location)",
    "Describe an item using 7/7 descriptors (e.g., category, function, appearance, parts, location)",
    "State 2 differences",
    "State 3 differences",
    "State 4 differences",
    "State 5 differences",
    "State 2 similarities",
    "State 3 similarities",
    "State 4 similarities",
    "State 5 similarities",
    "Compare/contrast (providing 2 similarities/differences)",
    "Compare/contrast (providing 4 similarities/differences)",
    "Compare/contrast (providing 5 similarities/differences)",
    "Name the antonym",
    "Name the synonym",
    "State the meaning of a root word",
    "State the meaning of a prefix",
    "State the meaning of a suffix",
    "State the meaning of an unknown word using word parts",
  ],
};

export default GOAL_BANK;

